#!/usr/bin/python3

# --- BEGIN COPYRIGHT BLOCK ---
# Copyright (C) 2016 Red Hat, Inc.
# All rights reserved.
#
# License: GPL (version 3 or any later version).
# See LICENSE for details.
# --- END COPYRIGHT BLOCK ---

import argparse
import logging
import ldap
import sys

from lib389 import DirSrv
from lib389.cli_conf import backend as cli_backend
from lib389.cli_base import disconnect_instance, connect_instance

logging.basicConfig()
log = logging.getLogger("dsconf")

if __name__ == '__main__':

    defbase = ldap.get_option(ldap.OPT_DEFBASE)

    parser = argparse.ArgumentParser()
    # Build the base ldap options, this keeps in unified.

    parser.add_argument('-D', '--binddn',
            help="The account to bind as for executing operations",
            default=None,
        )
    parser.add_argument('-H', '--ldapurl',
            help="The LDAP url to connect to, IE ldap://mai.example.com:389",
            default=None,
        )
    parser.add_argument('-b', '--basedn',
            help="The basedn for this operation.",
            default=None,
        )
    parser.add_argument('-Z', '--starttls',
            help="Connect with StartTLS",
            default=False, action='store_true'
        )
    parser.add_argument('-v', '--verbose',
            help="Display verbose operation tracing during command execution",
            action='store_true', default=False
        )

    subparsers = parser.add_subparsers(help="resources to act upon")

    cli_backend.create_parser(subparsers)

    args = parser.parse_args()

    if args.verbose:
        log.setLevel(logging.DEBUG)
    else:
        log.setLevel(logging.INFO)

    log.debug("The 389 Directory Server Configuration Tool")
    # Leave this comment here: UofA let me take this code with me provided
    # I gave attribution. -- wibrown
    log.debug("Inspired by works of: ITS, The University of Adelaide")

    log.debug("Called with: %s", args)

    # Assert we have a resources to work on.
    if not hasattr(args, 'func'):
        log.error("No resource provided to act upon")
        log.error("USAGE: dsadm [options] <resource> <action> [action options]")
        sys.exit(1)

    # Connect
    inst = None
    if args.verbose:
        inst = connect_instance(args.ldapurl, args.binddn, args.verbose, args.starttls)
        args.func(inst, args.basedn, log, args)
    else:
        try:
            inst = connect_instance(args.ldapurl, args.binddn, args.verbose, args.starttls)
            args.func(inst, args.basedn, log, args)
        except Exception as e:
            log.debug(e, exc_info=True)
            log.error("Error: %s" % e)
    disconnect_instance(inst)

    # Done!
    log.debug("dsconf is brought to you by the letter H and the number 25.")


