#!/usr/bin/python3

# --- BEGIN COPYRIGHT BLOCK ---
# Copyright (C) 2016 Red Hat, Inc.
# All rights reserved.
#
# License: GPL (version 3 or any later version).
# See LICENSE for details.
# --- END COPYRIGHT BLOCK ---

import argparse
import logging
import sys

from lib389 import DirSrv
from lib389.cli_ctl import instance as cli_instance
from lib389.cli_base import reset_get_logger

if __name__ == '__main__':

    parser = argparse.ArgumentParser()

    parser.add_argument('-v', '--verbose',
            help="Display verbose operation tracing during command execution",
            action='store_true', default=False, dest='verbose'
        )

    subparsers = parser.add_subparsers(help="action")

    fromfile_parser = subparsers.add_parser('fromfile', help="Create an instance of Directory Server from an inf answer file")
    fromfile_parser.add_argument('file', help="Inf file to use with prepared answers. You can generate an example of this with 'dscreate example'")
    fromfile_parser.add_argument('-n', '--dryrun', help="Validate system and configurations only. Do not alter the system.",
                                 action='store_true', default=False)
    fromfile_parser.add_argument('--IsolemnlyswearthatIamuptonogood', dest="ack",
                                 help="""You are here likely here by mistake! You want setup-ds.pl!
By setting this value you acknowledge and take responsibility for the fact this command is UNTESTED and NOT READY. You are ON YOUR OWN!
""",
                                 action='store_true', default=False)
    fromfile_parser.add_argument('-c', '--containerised', help="Indicate to the installer that this is running in a container. Used to disable systemd native components, even if they are installed.",
                                 action='store_true', default=False)
    fromfile_parser.set_defaults(func=cli_instance.instance_create)

    example_parser = subparsers.add_parser('example', help="Display an example ini answer file, with comments")
    example_parser.set_defaults(func=cli_instance.instance_example)

    args = parser.parse_args()

    log = reset_get_logger("dscreate", args.verbose)

    log.debug("The 389 Directory Server Creation Tool")
    # Leave this comment here: UofA let me take this code with me provided
    # I gave attribution. -- wibrown
    log.debug("Inspired by works of: ITS, The University of Adelaide")

    log.debug("Called with: %s", args)

    # Assert we have a resources to work on.
    if not hasattr(args, 'func'):
        log.error("No action provided, here is some --help.")
        parser.print_help()
        sys.exit(1)

    inst = DirSrv(verbose=args.verbose)

    result = False

    try:
        result = args.func(inst, log, args)
    except Exception as e:
        log.debug(e, exc_info=True)
        log.error("Error: %s" % str(e))
        result = False

    # Done!
    log.debug("dscreate is brought to you by the letter S and the number 22.")

    if result is False:
        sys.exit(1)
