#!/bin/sh
#
# BEGIN COPYRIGHT BLOCK
# This Program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 2 of the License.
# 
# This Program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# this Program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA.
# 
# In addition, as a special exception, Red Hat, Inc. gives You the additional
# right to link the code of this Program with code not covered under the GNU
# General Public License ("Non-GPL Code") and to distribute linked combinations
# including the two, subject to the limitations in this paragraph. Non-GPL Code
# permitted under this exception must only link to the code of this Program
# through those well defined interfaces identified in the file named EXCEPTION
# found in the source code files (the "Approved Interfaces"). The files of
# Non-GPL Code may instantiate templates or use macros or inline functions from
# the Approved Interfaces without causing the resulting work to be covered by
# the GNU General Public License. Only Red Hat, Inc. may make changes or
# additions to the list of Approved Interfaces. You must obey the GNU General
# Public License in all respects for all of the Program code and other code used
# in conjunction with the Program except the Non-GPL Code covered by this
# exception. If you modify this file, you may extend this exception to your
# version of the file, but you are not obligated to do so. If you do not wish to
# provide this exception without modification, you must delete this exception
# statement from your version and license this file solely under the GPL without
# exception. 
# 
# 
# Copyright (C) 2001 Sun Microsystems, Inc. Used by permission.
# Copyright (C) 2005 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK
#

# We still have 32 bit applications shipped with the 64 bit DS
# that need to access secmod.db and the root certs file
# nssckbi shared library.  However, 32 bit apps cannot load
# the 64 bit version of this shared library.  This script
# changes secmod.db to have both the 32 bit and 64 bit versions
# of nssckbi.

# The first argument is the name of the directory where secmod.db
# and the nssckbi shared libraries (64 bit and 32 bit) are.  If
# secmod.db does not exist an error will occur.

# The second argument is the path of the modutil
# command.  If the path is omitted then PATH will be used.

usage()
{
	echo Error: $1
	echo The first argument is the name of the directory where secmod.db
	echo and the nssckbi shared libraries '(64 bit and 32 bit)' are.  If
	echo secmod.db does not exist an error will occur.
	echo The second argument is the path where the modutil command
	echo is found.
}

dir="$1"
shift
modutildir="$1"
modutil=$modutildir/modutil
LD_LIBRARY_PATH=$modutildir/../lib:$LD_LIBRARY_PATH
SHLIB_PATH=$modutildir/../lib:$SHLIB_PATH
export LD_LIBRARY_PATH SHLIB_PATH

# see if correct argument was given
if test \! \( "$dir" -a -d "$dir" \) ; then
	usage "Invalid directory $dir"
	exit 1
fi

# see if the files are there

lib64=$dir/*nssckbi.*
lib32=$dir/*nssckbi32.*

if test \! \( -f $lib64 -a -f $lib32 \) ; then
	usage "Files $lib64 and/or $lib32 do not exist in dir $dir"
	exit 2
fi

if test \! -f $dir/secmod.db ; then
	usage "$dir/secmod.db does not exist"
	exit 3
fi

modname="Root Certs 32 bit"

# see if the module already exists
exists=0
$modutil -force -nocertdb -dbdir $dir -list | grep "$modname" > /dev/null 2>&1 && exists=1

if test $exists -ne 1 ; then
	$modutil -force -nocertdb -dbdir $dir -add "$modname" -libfile $lib32 || usage "Could not add $modname to $dir/secmod.db: $?"
else
	echo "Module $modname already added to secmod.db"
fi
