#!perl
#
# BEGIN COPYRIGHT BLOCK
# This Program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 2 of the License.
# 
# This Program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# this Program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA.
# 
# In addition, as a special exception, Red Hat, Inc. gives You the additional
# right to link the code of this Program with code not covered under the GNU
# General Public License ("Non-GPL Code") and to distribute linked combinations
# including the two, subject to the limitations in this paragraph. Non-GPL Code
# permitted under this exception must only link to the code of this Program
# through those well defined interfaces identified in the file named EXCEPTION
# found in the source code files (the "Approved Interfaces"). The files of
# Non-GPL Code may instantiate templates or use macros or inline functions from
# the Approved Interfaces without causing the resulting work to be covered by
# the GNU General Public License. Only Red Hat, Inc. may make changes or
# additions to the list of Approved Interfaces. You must obey the GNU General
# Public License in all respects for all of the Program code and other code used
# in conjunction with the Program except the Non-GPL Code covered by this
# exception. If you modify this file, you may extend this exception to your
# version of the file, but you are not obligated to do so. If you do not wish to
# do so, delete this exception statement from your version. 
# 
# 
# Copyright (C) 2001 Sun Microsystems, Inc. Used by permission.
# Copyright (C) 2005 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK
#

# makevlvsearch

sub usage_and_exit
{
    print "makevlvsearch [options]\n";
    print "\n";
    print "May be used to create just a vlvSearch entry, or to create\n";
    print "both a vlvSearch and vlvIndex entry.\n";
    print "\n";
    print "Options:\n";
    print "-?              - help\n";
    print "-D rootdn       - Provide a root DN.  Default= '$rootdn'\n";
    print "-w password     - Provide a password for the root DN.\n";
    print "-h host         - Provide a host name. Default= '$host'\n";
    print "-p port         - Provide a port. Default= '$port'\n";
    print "-b scope        - Provide a scope. 1 or 2. Default= '$vlvscope'\n";
    print "-f filter       - Provide a search filter. Default= '$vlvfilter'\n";
    print "-sn search_name - RDN of the vlvSearch parent entry.\n";
    print "-in index_name  - RDN for the vlvIndex child entry.\n";
    print "-s sort         - Provide a sort specification. Default='$vlvsort'\n";
    exit;
}

# Initialise some things
$vlvsearch_name= "";
$vlvindex_name= "";
$vlvscope= "2";
$vlvfilter= "(objectclass=*)";
$vlvsort= "";
$rootdn= "cn=Directory Manager";
$host= "localhost";
$port= "389";

# Process the command line arguments
while( $arg = shift)
{
    if($arg eq "-?")
    {
        usage_and_exit();
    }
    elsif($arg eq "-D")
    {
        $rootdn= shift @ARGV;
    }
    elsif($arg eq "-w")
    {
        $rootpw= shift @ARGV;
    }
    elsif($arg eq "-h")
    {
        $host= shift @ARGV;
    }
    elsif($arg eq "-p")
    {
        $port= shift @ARGV;
    }
    elsif($arg eq "-b")
    {
        $vlvscope= shift @ARGV;
    }
    elsif($arg eq "-f")
    {
        $vlvfilter= shift @ARGV;
    }
    elsif($arg eq "-s")
    {
        $vlvsort= shift @ARGV;
    }
    elsif($arg eq "-sn")
    {
        $vlvsearch_name= shift @ARGV;
    }
    elsif($arg eq "-in")
    {
        $vlvindex_name= shift @ARGV;
    }
    else
    {
        print "$arg: Unknown command line argument.\n";
    }
}

$ldapmodify= "ldapmodify -h $host -p $port -D \"$rootdn\" -w $rootpw";

if( $vlvfilter eq "" ||
    $vlvscope eq "" ||
    $vlvsearch_name eq "" ||
    $rootdn eq "" ||
    $host eq "" ||
    $port eq "")
{
    print "Error: Need command line information..\n";
    usage_and_exit();
}

if( $rootpw eq "" )
{
    print "Warning: No root DN password provided.  Won't be able to add VLV Search and Index entries.\n";
}

# Tell the user what we're up to.
print "Adding VLV Search and Index entries.\n";

# Build the vlv search and index entries to be added.
@vlvsearch= ( 
            "dn: cn=$vlvsearch_name, cn=config, cn=ldbm\n",
            "objectclass: top\n",
            "objectclass: vlvSearch\n",
            "cn: $vlvsearch_name\n",
            "vlvbase: $dn\n",
            "vlvfilter: $vlvfilter\n",
            "vlvscope: $vlvscope\n\n" );

@vlvindex= (
            "dn: cn=$vlvindex_name, cn=$vlvsearch_name, cn=config, cn=ldbm\n",
            "objectclass: top\n",
            "objectclass: vlvIndex\n",
            "cn: $vlvindex_name\n",
            "vlvsort: $vlvsort\n\n" );

open(FD,"| $ldapmodify -a -c");
print FD @vlvsearch;
if( not($vlvindex_name eq "" || $vlvsort eq ""))
{
    print FD @vlvindex;
}
close(FD);


