#!perl
#
# BEGIN COPYRIGHT BLOCK
# This Program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 2 of the License.
# 
# This Program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# this Program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA.
# 
# In addition, as a special exception, Red Hat, Inc. gives You the additional
# right to link the code of this Program with code not covered under the GNU
# General Public License ("Non-GPL Code") and to distribute linked combinations
# including the two, subject to the limitations in this paragraph. Non-GPL Code
# permitted under this exception must only link to the code of this Program
# through those well defined interfaces identified in the file named EXCEPTION
# found in the source code files (the "Approved Interfaces"). The files of
# Non-GPL Code may instantiate templates or use macros or inline functions from
# the Approved Interfaces without causing the resulting work to be covered by
# the GNU General Public License. Only Red Hat, Inc. may make changes or
# additions to the list of Approved Interfaces. You must obey the GNU General
# Public License in all respects for all of the Program code and other code used
# in conjunction with the Program except the Non-GPL Code covered by this
# exception. If you modify this file, you may extend this exception to your
# version of the file, but you are not obligated to do so. If you do not wish to
# do so, delete this exception statement from your version. 
# 
# 
# Copyright (C) 2001 Sun Microsystems, Inc. Used by permission.
# Copyright (C) 2005 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK
#
#
# Convert an old password.txt file into the new pin.txt format
# This script requires a single argument which is the directory and
# server instance prefix of the two files (e.g. /servers/alias/slapd-foo)
#
# ISSUES:
#   This code sets the mode of the created file to 660 (allows suitespot
#   group access.  Should it also set the user and group values? Where
#   should they come from?
#
BEGIN {
	$isNT = -d "\\";
	$PS = $isNT ? "\\" : "/";
}

$sroot = $ARGV[0];
$prefix = $ARGV[1];

#
# create the names for the old (password) and new (pin) files
#
$pwdfile = "${prefix}-password.txt";
$pinfile = "${prefix}-pin.txt";

if (-f $pwdfile && ! -f $pinfile) {
    open(PWDFILE, $pwdfile) || die "Cannot open password file: $pwdfile\n";

    my $count = 0;
	my $pin;
	while(<PWDFILE>) {
		chomp;  # trim new line

		if ($count == 0) {
			$pin = $_; 
		}

		$count = $count+1;
	}
	close PWDFILE;

    if ($count == 0) {
		die "No password found in password file\n";
	} elsif ($count != 1) {
		print "Extra lines found in password file\n";
    }

	open(PINFILE, ">$pinfile") || die "Cannot create pin file: $pinfile\n";
	print PINFILE "Software (Internal) Token:$pin\n";
	close PINFILE;
    chmod 0660, $pinfile;

	# set the ownership of the file; should be the same as the slapd user id
	if (! $isNT) {
		$confFile = "$sroot${PS}$prefix${PS}config${PS}slapd.conf";
		open(CONF, $confFile) or die "Error: cannot open $confFile: $!";
		while (<CONF>) {
			if (/^localuser\s+/i) {
				chomp($newuser = $');
				last;
			}
		}
		close(CONF);
		if (!$newuser) {
			$confFile = "$sroot${PS}shared${PS}config${PS}ssusers.conf";
			open(SSUSERS, $confFile) or
				die "Error: could not open $confFile: $!";
			while (<SSUSERS>) {
				chop;
				if (/^SuiteSpotUser\s+/i) {
					$newuser = $';
					last;
				}
			}
			close(SSUSERS);
		}
		if ($newuser) {
			chown $newuser, $pinfile;
		}
	}
}

exit 0;
