.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DIRSRV 5 "Jun 26, 2018"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME 
/etc/sysconfig/dirsrv - Systemd EnvironmentFile that affects all Directory Server instances.

.SH SYNOPSIS
/etc/sysconfig/dirsrv

.SH DESCRIPTION
dirsrv

This file is sourced by dirsrv upon startup to set
the default environment for all directory server instances.
To set instance specific defaults, use the file in the same
directory called dirsrv-instance where "instance"
is the name of your directory server instance e.g.
dirsrv-localhost for the slapd-localhost instance.

This file is in systemd EnvironmentFile format - see man systemd.exec

.SH EXAMPLE
LD_PRELOAD=/usr/lib64/dirsrv/lib/libjemalloc.so.2


.SH AUTHOR
dirsrv was written by the 389 Project.
.SH "REPORTING BUGS"
Report bugs to https://github.com/389ds/389-ds-base/issues/new
.SH COPYRIGHT
Copyright \(co 2018 Red Hat, Inc.

