#!/bin/ksh
#
# BEGIN COPYRIGHT BLOCK
# This Program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 2 of the License.
# 
# This Program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# this Program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA.
# 
# In addition, as a special exception, Red Hat, Inc. gives You the additional
# right to link the code of this Program with code not covered under the GNU
# General Public License ("Non-GPL Code") and to distribute linked combinations
# including the two, subject to the limitations in this paragraph. Non-GPL Code
# permitted under this exception must only link to the code of this Program
# through those well defined interfaces identified in the file named EXCEPTION
# found in the source code files (the "Approved Interfaces"). The files of
# Non-GPL Code may instantiate templates or use macros or inline functions from
# the Approved Interfaces without causing the resulting work to be covered by
# the GNU General Public License. Only Red Hat, Inc. may make changes or
# additions to the list of Approved Interfaces. You must obey the GNU General
# Public License in all respects for all of the Program code and other code used
# in conjunction with the Program except the Non-GPL Code covered by this
# exception. If you modify this file, you may extend this exception to your
# version of the file, but you are not obligated to do so. If you do not wish to
# provide this exception without modification, you must delete this exception
# statement from your version and license this file solely under the GPL without
# exception. 
# 
# 
# Copyright (C) 2001 Sun Microsystems, Inc. Used by permission.
# Copyright (C) 2005 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK
#
# setup for test
USERDN="cn=Harry Miller, ou=Human Resources, o=Ace Industry, c=US"
USER2DN="cn=Sam Carter, ou=Accounting, o=Ace Industry, c=US"

UID="hmiller"
U2ID="scarter"

GROUPDN="cn=Directory Administrators, o=Ace Industry, c=US"
GROUPID="Directory Administrators"

ATTRFILTER="mail=hmiller@aceindustry.com"
ATTR2FILTER="mail=scarter@aceindustry.com"

function check_result {
  echo "\nStart of test: $1 $2 \"$3\" \"$4\""
  if ( `$1 $2 "$3" "$4"` ) then
    if [ $5 == "fail" ]; then
      echo "**** Test Failed ****";
    else
      echo "Test Succeeded";
    fi
  else
    if [ $5 == "fail" ]; then
      echo "Test Succeeded";
    else
      echo "**** Test Failed ****";
    fi
  fi
}

function must_fail {
  check_result $1 $2 "$3" "$4" "fail";
}

function must_succeed {
  check_result $1 $2 "$3" "$4" "success";
}

# test for <userdn> <groupdn>
must_succeed ./auth 1 "${USERDN}" "${GROUPDN}"
must_fail ./auth 1 "${USER2DN}" "${GROUPDN}"

# test for <uid> <groupdn>
must_succeed ./auth 2 "${UID}" "${GROUPDN}"
must_fail ./auth 2 "${U2ID}" "${GROUPDN}"

# test for <uid> <groupid>
must_succeed ./auth 3 "${UID}" "${GROUPID}"
must_fail ./auth 3 "${U2ID}" "${GROUPID}"

# test for <userdn> <groupid>
must_succeed ./auth 4 "${USERDN}" "${GROUPID}"
must_fail ./auth 4 "${USER2DN}" "${GROUPID}"
must_succeed ./auth 15 "${USERDN}" "${GROUPID}"
must_fail ./auth 15 "${USER2DN}" "${GROUPID}"
must_succeed ./auth 16 "{${USERDN}" "${GROUPID}"
must_fail ./auth 16 "{${USER2DN}" "${GROUPID}"

# test for <userdn> <attrFilter>
must_succeed ./auth 5 "${USERDN}" "${ATTRFILTER}"
must_fail ./auth 5 "${USERDN}" "${ATTR2FILTER}"
must_fail ./auth 5 "${USER2DN}" "${ATTRFILTER}"

# test for <uid> <attrFilter>
must_succeed ./auth 6 "${UID}" "${ATTRFILTER}"
must_fail ./auth 6 "${UID}" "${ATTR2FILTER}"
must_fail ./auth 6 "${U2ID}" "${ATTRFILTER}"

# test for <userdn> <password>
must_succeed ./auth 7 "${USERDN}" "hillock"
must_fail ./auth 7 "${USERDN}" "garbage"

# test for <uid> <password>
must_succeed ./auth 8 "${UID}" "hillock"
must_fail ./auth 8 "${UID}" "garbage"

#test for cert to ldap entry mapping
must_succeed ./auth 9 "o=Ace Industry, c=US" "cn=Kirsten Vaughan, ou=Human Resources, o=Ace Industry, c=US"
#must_fail ./auth 9 "default" "cn=Kirsten Vaughan, o=Ace Industry, c=US"

# test for encode/decode bindpw
must_succeed ./auth 10 "cn=Foo Bar, o=$VENDOR, c=US" "foobar"

# test for reading dbnames from dbswitch.conf file
must_succeed ./auth 11 dblist.conf ignore

# test for saving certmap info
must_succeed ./auth 12 certmap.new certmap.conf
cat certmap.conf certmap.new 1>&2

# test for delete certmap info
must_succeed ./auth 13 certmap.new certmap.conf
cat certmap.conf certmap.new 1>&2

# test for add certmap info
must_succeed ./auth 14 certmap.new certmap.conf
cat certmap.conf certmap.new 1>&2

