/* --- BEGIN COPYRIGHT BLOCK ---
 * Copyright (C) 2001 Sun Microsystems, Inc. Used by permission.
 * Copyright (C) 2005 Red Hat, Inc.
 * All rights reserved.
 *
 * License: GPL (version 3 or any later version).
 * See LICENSE for details.
 * --- END COPYRIGHT BLOCK --- */

#ifdef HAVE_CONFIG_H
#include <config.h>
#endif

/* This list was generated by /tmp/getHPPatches.pl */
/*   on epsilon3.redhat.com
 */
/*   at Tue Aug  7 19:56:54 2007 GMT */
/* Here is the information from uname -a:
HP-UX epsilon3 B.11.23 U ia64 1756071376 unlimited-user license
QPKBASE         B.11.23.0706.064
Base
Quality Pack Bundle for HP-UX 11i v2
 The following is a Quality Pack installed on the system. */
{"QPKBASE               B.11.23.0706.064", "Base", "Quality Pack Bundle for HP-UX 11i v2", 2007, 6, 0},
