/* --- BEGIN COPYRIGHT BLOCK ---
 * This Program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License as published by the Free Software
 * Foundation; version 2 of the License.
 * 
 * This Program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along with
 * this Program; if not, write to the Free Software Foundation, Inc., 59 Temple
 * Place, Suite 330, Boston, MA 02111-1307 USA.
 * 
 * In addition, as a special exception, Red Hat, Inc. gives You the additional
 * right to link the code of this Program with code not covered under the GNU
 * General Public License ("Non-GPL Code") and to distribute linked combinations
 * including the two, subject to the limitations in this paragraph. Non-GPL Code
 * permitted under this exception must only link to the code of this Program
 * through those well defined interfaces identified in the file named EXCEPTION
 * found in the source code files (the "Approved Interfaces"). The files of
 * Non-GPL Code may instantiate templates or use macros or inline functions from
 * the Approved Interfaces without causing the resulting work to be covered by
 * the GNU General Public License. Only Red Hat, Inc. may make changes or
 * additions to the list of Approved Interfaces. You must obey the GNU General
 * Public License in all respects for all of the Program code and other code used
 * in conjunction with the Program except the Non-GPL Code covered by this
 * exception. If you modify this file, you may extend this exception to your
 * version of the file, but you are not obligated to do so. If you do not wish to
 * provide this exception without modification, you must delete this exception
 * statement from your version and license this file solely under the GPL without
 * exception. 
 * 
 * 
 * Copyright (C) 2001 Sun Microsystems, Inc. Used by permission.
 * Copyright (C) 2005 Red Hat, Inc.
 * All rights reserved.
 * --- END COPYRIGHT BLOCK --- */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif


/* This list was generated by /u/norikoyasuo/bin/getSolPatches.pl */
/*   on droid.mcom.com */
/*   at Thu Mar 18 18:34:27 2004 GMT */
/* Here is the information from /etc/release:
                           Solaris 8 s28_38shwp2 SPARC
           Copyright 2000 Sun Microsystems, Inc.  All Rights Reserved.
                            Assembled 21 January 2000
 The following is a list of patches installed on the system */
/* a patch that is commented out is either a duplicate or */
/* a patch that is superseded by another patch */
{108434,14,1,28,0,0,"Jan/16/2004: SunOS 5.8: 32-Bit Shared library patch for C++"},
{108435,14,1,28,0,0,"Jan/16/2004: SunOS 5.8: 64-Bit Shared library patch for C++"},
{108528,27,1,28,0,0,"Nov/25/2003: SunOS 5.8: kernel update patch"},
{108652,77,1,28,0,0,"Jan/26/2004: X11 6.4.1: Xsun patch"},
{108725,15,1,28,0,0,"Jan/23/2004: SunOS 5.8: st driver patch"},
{108727,26,1,28,0,0,"Dec/02/2003: SunOS 5.8: /kernel/fs/nfs and /kernel/fs/sparcv9/nfs patch"},
{108806,17,1,28,0,0,"Aug/12/2003: SunOS 5.8: Sun Quad FastEthernet qfe driver"},
{108827,20,1,28,0,0,"Mar/20/2002: SunOS 5.8: /usr/lib/libthread.so.1 patch"},
{108869,22,1,28,0,0,"Aug/19/2003: SunOS 5.8: snmpdx/mibiisa/libssasnmp/snmplib patch"},
{108875,12,1,28,0,0,"Apr/10/2002: SunOS 5.8: c2audit patch"},
{108899,4,1,28,0,0,"Feb/18/2003: SunOS 5.8: /usr/bin/ftp patch"},
{108901,4,1,28,0,0,"Jul/23/2001: SunOS 5.8: /kernel/sys/rpcmod and /kernel/strmod/rpcmod patch"},
{108919,20,1,28,0,0,"Sep/22/2003: CDE 1.4: dtlogin patch"},
{108949,7,1,28,0,0,"Dec/07/2001: CDE 1.4: libDtHelp/libDtSvc patch"},
{108968,8,1,28,0,0,"Jan/22/2003: SunOS 5.8: vol/vold/rmmount/dev_pcmem.so.1 patch"},
{108974,37,1,28,0,0,"Jan/07/2004: SunOS 5.8: dada, uata, dad, sd, ssd and scsi drivers patch"},
{108975,8,1,28,0,0,"Apr/18/2003: SunOS 5.8: /usr/bin/rmformat and /usr/sbin/format patch"},
{108977,2,1,28,0,0,"Apr/18/2003: SunOS 5.8: libsmedia patch"},
{108981,13,1,28,0,0,"Nov/25/2003: SunOS 5.8: /kernel/drv/hme and /kernel/drv/sparcv9/hme patch"},
{108985,3,1,28,0,0,"Jun/25/2001: SunOS 5.8: /usr/sbin/in.rshd patch"},
{108987,13,1,28,0,0,"Apr/07/2003: SunOS 5.8: Patch for patchadd and patchrm"},
{108989,2,1,28,0,0,"Jul/18/00: SunOS 5.8: /usr/kernel/sys/acctctl and /usr/kernel/sys/exacctsys patch"},
{108993,31,1,28,0,0,"Dec/10/2003: SunOS 5.8: LDAP2 client, libc, libthread and libnsl libraries patch"},
{108997,3,1,28,0,0,"Jul/18/00: SunOS 5.8: libexacct and libproject patch"},
{109007,15,1,28,0,0,"Jan/27/2004: SunOS 5.8: at/atrm/batch/cron patch"},
{109091,6,1,28,0,0,"Apr/08/2003: SunOS 5.8: /usr/lib/fs/ufs/ufsrestore patch"},
/* Web-Based Enterprise Management (WBEM) {109134,28,1,28,0,0,"Jun/10/2003: SunOS 5.8: WBEM patch"}, */
{109147,27,1,28,0,0,"Nov/26/2003: SunOS 5.8: linker patch"},
{109149,2,1,28,0,0,"Nov/13/2001: SunOS 5.8:: /usr/sbin/mkdevmaps and /usr/sbin/mkdevalloc patch"},
{109152,2,1,28,0,0,"Mar/27/2003: SunOS 5.8: /usr/4lib/libc.so.x.9 and libdbm patch"},
{109202,5,1,28,0,0,"Jun/06/2003: SunOS 5.8: /kernel/misc/gld and /kernel/misc/sparcv9/gld patch"},
{109223,4,1,28,0,0,"Dec/23/2003: SunOS 5.8: kpasswd, libgss.so.1 and libkadm5clnt.so.1 patch"},
{109234,9,1,28,0,0,"Aug/07/2002: SunOS 5.8: Apache Security and NCA Patch"},
{109238,2,1,28,0,0,"Sep/17/2001: SunOS 5.8: /usr/bin/sparcv7/ipcs and /usr/bin/sparcv9/ipcs patch"},
{109277,3,1,28,0,0,"Oct/25/2002: SunOS 5.8: /usr/bin/iostat patch"},
{109318,34,1,28,0,0,"Nov/14/2003: SunOS 5.8: suninstall Patch"},
{109320,8,1,28,0,0,"Nov/26/2003: SunOS 5.8: LP Patch"},
{109324,5,1,28,0,0,"Dec/05/2002: SunOS 5.8: sh/jsh/rsh/pfsh patch"},
{109326,13,1,28,0,0,"Jan/29/2004: SunOS 5.8: libresolv.so.2 and in.named patch"},
{109328,3,1,28,0,0,"Oct/29/2002: SunOS 5.8: ypserv, ypxfr and ypxfrd patch"},
{109354,19,1,28,0,0,"Apr/15/2003: CDE 1.4: dtsession patch"},
{109458,3,1,28,0,0,"Jan/07/2003: SunOS 5.8: /kernel/strmod/ldterm patch"},
{109460,10,1,28,0,0,"Aug/04/2003: SunOS 5.8: socal and sf drivers patch"},
{109470,2,1,28,0,0,"Aug/29/00: CDE 1.4: Actions Patch"},
{109657,9,1,28,0,0,"Jan/07/2003: SunOS 5.8: isp driver patch"},
{109667,5,1,28,0,0,"Jun/16/2003: SunOS 5.8: /usr/lib/inet/xntpd and /usr/sbin/ntpdate patch"},
{109695,3,1,28,0,0,"Jul/23/2001: SunOS 5.8: /etc/smartcard/opencard.properties patch"},
{109778,14,1,28,0,0,"Jan/26/2004: SunOS 5.8: Misc loc have errors in CTYPE and lv colln monetary"},
{109783,2,1,28,0,0,"Oct/02/2002: SunOS 5.8: /usr/lib/nfs/nfsd and /usr/lib/nfs/lockd patch"},
{109793,23,1,28,0,0,"Oct/13/2003: SunOS 5.8: su driver patch"},
{109805,17,1,28,0,0,"Sep/29/2003: SunOS 5.8: /usr/lib/security/pam_krb5.so.1 patch"},
{109815,20,1,28,0,0,"Jan/07/2004: SunOS 5.8: se, acebus, pcf8574, pcf8591 and scsb patch"},
{109862,3,1,28,0,0,"Dec/18/2002: X11 6.4.1 Font Server patch"},
{109873,22,1,28,0,0,"Dec/04/2003: SunOS 5.8: prtdiag and platform libprtdiag_psr.so.1 patch"},
{109882,6,1,28,0,0,"Jun/05/2002: SunOS 5.8: eri header files patch"},
{109883,2,1,28,0,0,"Dec/20/2000: SunOS 5.8: /usr/include/sys/ecppsys.h patch"},
{109885,14,1,28,0,0,"Oct/01/2003: SunOS 5.8: glm patch"},
{109887,18,1,28,0,0,"Nov/17/2003: SunOS 5.8: smartcard and usr/sbin/ocfserv patch"},
{109888,26,1,28,0,0,"Nov/26/2003: SunOS 5.8: platform drivers patch"},
{109893,4,1,28,0,0,"Dec/24/2002: SunOS 5.8: stc driver patch"},
{109894,1,1,28,0,0,"Nov/15/2000: SunOS 5.8: /kernel/drv/sparcv9/bpp driver patch"},
{109896,24,1,28,0,0,"Feb/02/2004: SunOS 5.8: USB and Audio Framework patch"},
{109898,5,1,28,0,0,"Oct/22/2001: SunOS 5.8: /kernel/drv/arp patch"},
{109922,4,1,28,0,0,"Jan/22/2003: SunOS 5.8: pcelx and pcser driver patch"},
{109928,5,1,28,0,0,"Jun/27/2002: SunOS 5.8: pcmem and pcmcia patch"},
{110068,4,1,28,0,0,"Nov/05/2003: CDE 1.4: PDASync patch"},
{110075,1,1,28,0,0,"Mar/13/2001: SunOS 5.8: /kernel/drv/devinfo and /kernel/drv/sparcv9/devinfo patch"},
{110283,6,1,28,0,0,"Nov/26/2002: SunOS 5.8: mkfs and newfs patch"},
{110286,11,1,28,0,0,"Sep/24/2003: OpenWindows 3.6.2: Tooltalk patch"},
{110322,2,1,28,0,0,"Aug/19/2002: SunOS 5.8: /usr/lib/netsvc/yp/ypbind patch"},
{110335,3,1,28,0,0,"Dec/03/2003: CDE 1.4: dtprintinfo patch"},
{110380,4,1,28,0,0,"Dec/21/2001: SunOS 5.8: ufssnapshots support, libadm patch"},
{110386,3,1,28,0,0,"Apr/08/2003: SunOS 5.8: RBAC Feature Patch"},
{110387,5,1,28,0,0,"Aug/19/2003: SunOS 5.8: ufssnapshots support, ufsdump patch"},
{110389,5,1,28,0,0,"Jan/22/2003: SunOS 5.8: cvc CPU signature"},
{110453,4,1,28,0,0,"Feb/21/2003: SunOS 5.8: admintool Patch"},
{110458,2,1,28,0,0,"May/29/2001: SunOS 5.8: libcurses patch"},
{110460,32,1,28,0,0,"Nov/17/2003: SunOS 5.8: fruid/PICL plug-ins patch"},
{110461,3,1,28,0,0,"Feb/27/2003: SunOS 5.8: ttcompat patch"},
{110609,4,1,28,0,0,"Apr/18/2003: SunOS 5.8: cdio.h and command.h USB header patch"},
/* {110615,4,1,28,0,0,"Jan/23/2002: SunOS 5.8: sendmail patch"}, */
{110662,12,1,28,0,0,"Apr/24/2003: SunOS 5.8: ksh patch"},
{110668,4,1,28,0,0,"Apr/08/2003: SunOS 5.8: /usr/sbin/in.telnetd patch"},
/* rcp to non-solaris {110670,1,1,28,0,0,"Mar/30/2001: SunOS 5.8: usr/sbin/static/rcp patch"}, */
{110700,1,1,28,0,0,"Jan/08/2001: SunOS 5.8: automount patch"},
{110820,10,1,28,0,0,"Dec/19/2002: SunOS 5.8: /platform/SUNW,Sun-Fire-15000/kernel/drv/sparcv9/dman patch"},
{110838,6,1,28,0,0,"Dec/16/2002: SunOS 5.8: /platform/SUNW,Sun-Fire-15000/kernel/drv/sparcv9/axq patch"},
{110842,11,1,28,0,0,"May/08/2003: SunOS 5.8: hpc3130 driver patch for SUNW,Sun-Fire-880"},
{110896,2,1,28,0,0,"Jan/03/2003: SunOS 5.8: cachefs/mount patch"},
{110898,9,1,28,0,0,"Jan/26/2004: SunOS 5.8: csh/pfcsh patch"},
{110901,1,1,28,0,0,"Mar/02/2001: SunOS 5.8: /kernel/drv/sgen and /kernel/drv/sparcv9/sgen patch"},
{110903,7,1,28,0,0,"Nov/25/2003: SunOS 5.8: edit, ex, vedit, vi and view patch"},
{110916,5,1,28,0,0,"Dec/15/2003: SunOS 5.8: sort patch"},
{110934,14,1,28,0,0,"Aug/05/2003: SunOS 5.8: pkgtrans, pkgadd, pkgchk, pkgmk and libpkg.a patch"},
/* wtmp {110939,1,1,28,0,0,"Mar/06/2001: SunOS 5.8: /usr/lib/acct/closewtmp patch"}, */
{110943,2,1,28,0,0,"Nov/14/2003: SunOS 5.8: /usr/bin/tcsh patch"},
{110945,8,1,28,0,0,"May/29/2003: SunOS 5.8: /usr/sbin/syslogd patch"},
{110951,5,1,28,0,0,"Nov/14/2003: SunOS 5.8: /usr/sbin/tar and /usr/sbin/static/tar patch"},
{110953,6,1,28,0,0,"Dec/09/2003: SunOS 5.8: /usr/kernel/drv/llc2 patch"},
{110955,4,1,28,0,0,"Dec/24/2002: SunOS 5.8: /kernel/strmod/timod patch"},
{110957,2,1,28,0,0,"Nov/06/2001: SunOS 5.8: /usr/bin/mailx patch"},
{111023,3,1,28,0,0,"Dec/09/2003: SunOS 5.8: /kernel/fs/mntfs and /kernel/fs/sparcv9/mntfs patch"},
{111069,1,1,28,0,0,"Aug/02/2001: SunOS 5.8: bsmunconv overwrites root cron tab if cu created /tmp/root"},
/* uucp {111071,1,1,28,0,0,"Mar/30/2001: SunOS 5.8: cu patch"}, */
{111085,2,1,28,0,0,"Dec/13/2001: SunOS 5.8: /usr/bin/login patch"},
{111098,1,1,28,0,0,"Jul/17/2001: SunOS 5.8: ROC timezone should be avoided for political reasons"},
{111111,3,1,28,0,0,"Mar/28/2002: SunOS 5.8: /usr/bin/nawk patch"},
{111232,1,1,28,0,0,"Apr/25/2001: SunOS 5.8: patch in.fingerd"},
{111234,1,1,28,0,0,"Apr/25/2001: SunOS 5.8: patch finger"},
{111293,4,1,28,0,0,"Sep/25/2001: SunOS 5.8: /usr/lib/libdevinfo.so.1 patch"},
{111302,2,1,28,0,0,"Sep/11/2002: SunOS 5.8: EDHCP libraries patch"},
{111310,1,1,28,0,0,"Aug/21/2001: SunOS 5.8: /usr/lib/libdhcpagent.so.1 patch"},
{111317,5,1,28,0,0,"Dec/10/2003: SunOS 5.8: /sbin/init and /usr/sbin/init patch"},
{111321,3,1,28,0,0,"Oct/02/2002: SunOS 5.8: klmmod and klmops patch"},
{111325,2,1,28,0,0,"Jun/14/2002: SunOS 5.8: /usr/lib/saf/ttymon patch"},
{111327,5,1,28,0,0,"Dec/04/2001: SunOS 5.8: libsocket patch"},
{111400,2,1,28,0,0,"Jan/28/2004: SunOS 5.8: KCMS configure tool has a security vulnerability"},
{111504,1,1,28,0,0,"Jun/15/2001: SunOS 5.8: /usr/bin/tip patch"},
{111548,1,1,28,0,0,"Jun/15/2001: SunOS 5.8: catman, man, whatis, apropos and makewhatis patch"},
/* uucp {111570,2,1,28,0,0,"Sep/11/2002: SunOS 5.8: uucp patch"}, */
{111588,4,1,28,0,0,"Dec/24/2002: SunOS 5.8: /kernel/drv/ws and /kernel/fs/specfs patch"},
/* {111596,3,1,28,0,0,"Feb/28/2003: SunOS 5.8: /usr/lib/netsvc/yp/rpc.yppasswdd patch"}, */
{111606,4,1,28,0,0,"Jul/30/2003: SunOS 5.8: /usr/sbin/in.ftpd patch"},
{111624,4,1,28,0,0,"Oct/02/2002: SunOS 5.8: /usr/sbin/inetd patch"},
{111626,3,1,28,0,0,"Nov/11/2002: OpenWindows 3.6.2: Xview Patch"},
{111659,6,1,28,0,0,"Mar/04/2002: SunOS 5.8: passwd and pam_unix.so.1 patch"},
{111826,1,1,28,0,0,"Aug/15/2001: SunOS 5.8: /usr/sbin/sparcv7/whodo & /usr/sbin/sparcv9/whodo patch"},
{111874,6,1,28,0,0,"Jan/23/2003: SunOS 5.8: usr/bin/mail patch"},
/* old progreg and Live Upgrade problem {111879,1,1,28,0,0,"Aug/27/2001: SunOS 5.8: Solaris Product Registry patch SUNWwsr"}, */
{111881,3,1,28,0,0,"Dec/24/2002: SunOS 5.8: /usr/kernel/strmod/telmod patch"},
{111958,2,1,28,0,0,"May/13/2002: SunOS 5.8: /usr/lib/nfs/statd patch"},
{112039,1,1,28,0,0,"Sep/17/2001: SunOS 5.8: usr/bin/ckitem patch"},
{112138,1,1,28,0,0,"Nov/05/2001: SunOS 5.8:: usr/bin/domainname patch"},
{112161,3,1,28,0,0,"Dec/04/2003: SunOS 5.8: remove libprtdiag_psr.so.1 of SUNW,Netra-T12 SUNW,Netra-T4"},
{112218,1,1,28,0,0,"Nov/13/2001: SunOS 5.8:: pam_ldap.so.1 patch"},
{112237,9,1,28,0,0,"Nov/05/2003: SunOS 5.8: mech_krb5.so.1 patch"},
{112254,1,1,28,0,0,"Feb/27/2002: SunOS 5.8: /kernel/sched/TS patch"},
{112325,1,1,28,0,0,"Jan/22/2002: SunOS 5.8: /kernel/fs/udfs and /kernel/fs/sparcv9/udfs patch"},
{112396,2,1,28,0,0,"Mar/28/2002: SunOS 5.8: /usr/bin/fgrep patch"},
{112425,1,1,28,0,0,"Feb/19/2002: SunOS 5.8: /usr/lib/fs/ufs/mount and /etc/fs/ufs/mount patch"},
{112459,1,1,28,0,0,"Mar/07/2002: SunOS 5.8: /usr/lib/pt_chmod patch"},
{112609,2,1,28,0,0,"May/29/2003: SunOS 5.8: /kernel/drv/le and /kernel/drv/sparcv9/le patch"},
{112611,2,1,28,0,0,"Oct/21/2003: SunOS 5.8: /usr/lib/libz.so.1 patch"},
{112668,1,1,28,0,0,"May/14/2002: SunOS 5.8: /usr/bin/gzip patch"},
/* {112792,1,1,28,0,0,"Jul/09/2002: SunOS 5.8: /usr/lib/pcmciad patch"}, */
{112796,1,1,28,0,0,"May/27/2002: SunOS 5.8: /usr/sbin/in.talkd patch"},
{112846,1,1,28,0,0,"Jun/17/2002: SunOS 5.8: /usr/lib/netsvc/rwall/rpc.rwalld patch"},
{113648,3,1,28,0,0,"Dec/10/2003: SunOS 5.8: /usr/sbin/mount patch"},
{113650,2,1,28,0,0,"May/28/2003: SunOS 5.8: /usr/lib/utmp_update patch"},
{113685,5,1,28,0,0,"Oct/06/2003: SunOS 5.8: logindmux/ptsl/ms/bufmod/llc1/kb/zs/zsh/ptem patch"},
{113687,1,1,28,0,0,"Dec/24/2002: SunOS 5.8: /kernel/misc/kbtrans patch"},
{113792,1,1,28,0,0,"Nov/25/2002: OpenWindows 3.6.2: mailtool patch"},
{114162,1,1,28,0,0,"Apr/07/2003: SunOS 5.8: /kernel/drv/lofi drivers and /usr/sbin/lofiadm patch"},
{114673,1,1,28,0,0,"Apr/16/2003: SunOS 5.8: /usr/sbin/wall patch"},
{114802,2,1,28,0,0,"Jan/08/2004: SunOS 5.8: Patch for assembler"},
{114984,1,1,28,0,0,"Apr/29/2003: SunOS 5.8: /usr/kernel/fs/namefs patch"},
{115576,1,1,28,0,0,"Jul/28/2003: SunOS 5.8: /kernel/exec/elfexec and /kernel/exec/sparcv9/elfexec patch"},
{115797,1,1,28,0,0,"Aug/15/2003: CDE 1.4: dtspcd Patch"},
{115827,1,1,28,0,0,"Oct/27/2003: SunOS 5.8: /sbin/sulogin and /sbin/netstrategy patch"},
{116602,1,1,28,0,0,"Dec/10/2003: SunOS 5.8: /sbin/uadmin and /sbin/hostconfig patch"},
/* This list was generated by /u/norikoyasuo/bin/getSolPatches.pl */
/*   on tmolus.mcom.com */
/*   at Thu Mar 18 10:34:35 2004 GMT */
/* Here is the information from /etc/release:
                           Solaris 9 s9_58shwpl3 SPARC
           Copyright 2002 Sun Microsystems, Inc.  All Rights Reserved.
                        Use is subject to license terms.
                             Assembled 15 April 2002
 The following is a list of patches installed on the system */
/* a patch that is commented out is either a duplicate or */
/* a patch that is superseded by another patch */
{112233,11,1,29,0,0,"Dec/23/2003: SunOS 5.9: Kernel Patch"},
{112540,18,1,29,0,0,"Sep/02/2003: SunOS 5.9: Expert3D IFB Graphics Patch"},
{112601,9,1,29,0,0,"Oct/28/2003: SunOS 5.9: PGX32 Graphics"},
{112617,2,1,29,0,0,"Jan/15/2003: CDE 1.5: rpc.cmsd patch"},
{112661,6,1,29,0,0,"Oct/03/2003: SunOS 5.9: IIIM and X Input & Output Method patch"},
{112764,6,1,29,0,0,"Apr/16/2003: SunOS 5.9: Sun Quad FastEthernet qfe driver"},
{112785,30,1,29,0,0,"Dec/19/2003: X11 6.6.1: Xsun patch"},
{112807,7,1,29,0,0,"Sep/25/2003: CDE 1.5: dtlogin patch"},
{112808,6,1,29,0,0,"Dec/01/2003: CDE1.5: Tooltalk patch"},
{112817,16,1,29,0,0,"Jan/05/2004: SunOS 5.9: Sun GigaSwift Ethernet 1.0 driver patch"},
{112834,3,1,29,0,0,"Sep/01/2003: SunOS 5.9: patch scsi"},
{112874,22,1,29,0,0,"Jan/30/2004: SunOS 5.9: lgroup API libc Patch"},
{112875,1,1,29,0,0,"Jun/21/2002: SunOS 5.9: patch /usr/lib/netsvc/rwall/rpc.rwalld"},
{112902,8,1,29,0,0,"Dec/06/2002: SunOS 5.9: kernel/drv/ip Patch"},
{112907,2,1,29,0,0,"Oct/13/2003: SunOS 5.9: libgss Patch"},
{112908,11,1,29,0,0,"Nov/06/2003: SunOS 5.9: krb5 shared object Patch"},
{112921,3,1,29,0,0,"Jan/20/2004: SunOS 5.9: libkadm5 Patch"},
{112922,2,1,29,0,0,"Apr/24/2003: SunOS 5.9: krb5 lib Patch"},
{112923,3,1,29,0,0,"Nov/06/2003: SunOS 5.9: krb5 usr/lib Patch"},
{112925,3,1,29,0,0,"Nov/06/2003: SunOS 5.9: ktutil kdb5_util kadmin kadmin.local kadmind Patch"},
{112926,5,1,29,0,0,"Nov/17/2003: SunOS 5.9: smartcard Patch"},
{112945,21,1,29,0,0,"Jan/28/2004: SunOS 5.9: wbem Patch"},
{112951,4,1,29,0,0,"Dec/12/2002: SunOS 5.9: patchadd and patchrm Patch"},
{112960,10,1,29,0,0,"Dec/23/2003: SunOS 5.9: patch libsldap ldap_cachemgr libldap"},
{112963,10,1,29,0,0,"Oct/14/2003: SunOS 5.9: linker patch"},
{112964,4,1,29,0,0,"Apr/23/2003: SunOS 5.9: /usr/bin/ksh Patch"},
{112965,2,1,29,0,0,"Aug/01/2003: SunOS 5.9: patch /kernel/drv/sparcv9/eri"},
{112970,6,1,29,0,0,"Jan/13/2004: SunOS 5.9: patch libresolv"},
{112975,3,1,29,0,0,"Oct/24/2003: SunOS 5.9: patch /kernel/sys/kaio"},
{112998,3,1,29,0,0,"May/29/2003: SunOS 5.9: patch /usr/sbin/syslogd"},
{113026,14,1,29,0,0,"Jan/16/2004: SunOS 5.9: /kernel/drv/md Patch"},
{113030,2,1,29,0,0,"Dec/18/2002: SunOS 5.9: /kernel/sys/doorfs Patch"},
{113033,3,1,29,0,0,"Dec/24/2002: SunOS 5.9: patch /kernel/drv/isp and /kernel/drv/sparcv9/isp"},
{113068,4,1,29,0,0,"May/16/2003: SunOS 5.9: hpc3130 patch"},
{113073,5,1,29,0,0,"Sep/25/2003: SunOS 5.9: ufs_log patch"},
{113077,9,1,29,0,0,"Sep/24/2003: SunOS 5.9: /platform/sun4u/kernal/drv/su Patch"},
{113096,3,1,29,0,0,"May/01/2003: X11 6.6.1: OWconfig patch"},
{113146,2,1,29,0,0,"May/01/2003: SunOS 5.9: Apache Security Patch"},
{113240,5,1,29,0,0,"Jul/08/2003: CDE 1.5: dtsession patch"},
{113273,4,1,29,0,0,"Oct/08/2003: SunOS 5.9: /usr/lib/ssh/sshd Patch"},
{113277,17,1,29,0,0,"Oct/24/2003: SunOS 5.9: sd and ssd Patch"},
{113278,4,1,29,0,0,"Feb/02/2004: SunOS 5.9: NFS Daemon , rpcmod Patch"},
{113279,1,1,29,0,0,"Sep/17/2002: SunOS 5.9: klmmod Patch"},
{113319,17,1,29,0,0,"Dec/15/2003: SunOS 5.9: libnsl nispasswdd patch"},
{113329,5,1,29,0,0,"Jan/20/2004: SunOS 5.9: lp Patch"},
{113333,2,1,29,0,0,"Nov/18/2002: SunOS 5.9: libmeta Patch"},
{113451,6,1,29,0,0,"Jan/22/2004: SunOS 5.9: IKE Patch"},
{113454,14,1,29,0,0,"Nov/18/2003: SunOS 5.9: ufs Patch"},
{113464,6,1,29,0,0,"Sep/29/2003: SunOS 5.9: IPMP Headers Patch"},
{113492,4,1,29,0,0,"Dec/24/2003: SunOS 5.9: fsck Patch"},
{113573,3,1,29,0,0,"Aug/12/2003: SunOS 5.9: libpsvc Patch"},
{113574,3,1,29,0,0,"May/23/2003: SunOS 5.9: SUNW,Sun-Fire-880 libpsvc Patch"},
{113579,1,1,29,0,0,"Nov/08/2002: SunOS 5.9: ypserv/ypxfrd Patch"},
{113713,11,1,29,0,0,"Nov/04/2003: SunOS 5.9: pkginstall Patch"},
{113718,2,1,29,0,0,"Jun/04/2003: SunOS 5.9: usr/lib/utmp_update Patch"},
{113859,3,1,29,0,0,"Dec/24/2003: SunOS 5.9: Sun ONE Directory Server 5.1 patch"},
{113923,2,1,29,0,0,"Dec/18/2002: X11 6.6.1: security font server patch"},
{113993,6,1,29,0,0,"Sep/15/2003: SunOS 5.9: mkfs Patch"},
{114008,1,1,29,0,0,"Mar/19/2003: SunOS 5.9: cachefsd Patch"},
{114014,3,1,29,0,0,"Apr/01/2003: SunOS 5.9: libxml, libxslt and Freeware man pages Patch"},
{114016,1,1,29,0,0,"May/01/2003: tomcat security patch"},
{114125,1,1,29,0,0,"Aug/13/2003: SunOS 5.9: IKE config.sample patch"},
{114127,2,1,29,0,0,"Dec/24/2003: SunOS 5.9: abi_libefi.so.1 Patch"},
{114129,1,1,29,0,0,"Mar/31/2003: SunOS 5.9: multi-terabyte disk support -libuuid patch"},
{114133,1,1,29,0,0,"Feb/03/2003: SunOS 5.9: mail Patch"},
{114135,1,1,29,0,0,"Jan/22/2003: SunOS 5.9: at utility Patch"},
{114332,7,1,29,0,0,"Oct/01/2003: SunOS 5.9: c2audit & *libbsm.so.1 Patch"},
{114359,1,1,29,0,0,"Mar/03/2003: SunOS 5.9: mc-us3 Patch"},
{114361,1,1,29,0,0,"Apr/30/2003: SunOS 5.9: /kernel/drv/lofi Patch"},
{114363,2,1,29,0,0,"Jan/27/2004: SunOS 5.9: sort Patch"},
{114375,6,1,29,0,0,"Jul/25/2003: SunOS 5.9: Enchilada/Stiletto - PICL & FRUID"},
{114385,3,1,29,0,0,"Aug/04/2003: SunOS 5.9: Enchilada/Stiletto - pmugpio pmubus driver"},
{114482,4,1,29,0,0,"Sep/02/2003: SunOS 5.9: Product Registry CLI Revision"},
{114495,1,1,29,0,0,"Dec/03/2003: CDE 1.5: dtprintinfo patch"},
{114564,3,1,29,0,0,"Nov/14/2003: SunOS 5.9: /usr/sbin/in.ftpd Patch"},
{114569,2,1,29,0,0,"Apr/24/2003: SunOS 5.9: libdbm.so.1 Patch"},
{114571,1,1,29,0,0,"Apr/04/2003: SunOS 5.9: libc.so.*.9/bcp Patch"},
{114636,2,1,29,0,0,"Aug/06/2003: SunOS 5.9: KCMS security fix"},
{114684,2,1,29,0,0,"May/27/2003: SunOS 5.9: samba Patch"},
{114713,1,1,29,0,0,"Mar/26/2003: SunOS 5.9: newtask Patch"},
{114721,4,1,29,0,0,"Sep/15/2003: SunOS 5.9: ufsrestore and ufsdump Patch"},
{114729,1,1,29,0,0,"May/29/2003: SunOS 5.9: usr/sbin/in.telnetd Patch"},
{114861,1,1,29,0,0,"Apr/22/2003: SunOS 5.9: /usr/sbin/wall"},
{114864,2,1,29,0,0,"Jun/13/2003: SunOS 5.9: Sun-Fire-480R libpsvcpolicy_psr.so.1 Patch"},
{114971,1,1,29,0,0,"Sep/04/2003: SunOS 5.9: usr/kernel/fs/namefs Patch"},
{115172,1,1,29,0,0,"Sep/15/2003: SunOS 5.9: kernel/drv/le Patch"},
{115689,1,1,29,0,0,"Jan/27/2004: SunOS 5.9: /usr/lib/patch/patchutil Patch"},
{115754,2,1,29,0,0,"Oct/21/2003: SunOS 5.9: zlib security Patch"},
{116237,1,1,29,0,0,"Nov/26/2003: SunOS 5.9: pfexec Patch"},
{116245,1,1,29,0,0,"Jan/27/2004: SunOS 5.9: uncompress Patch"},
