#
# BEGIN COPYRIGHT BLOCK
# Copyright (C) 2001 Sun Microsystems, Inc. Used by permission.
# Copyright (C) 2005 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK
#
# OSF1 Makefile for Directory Server plug-in examples

CC = cc 
LD = ld

INCLUDE = -I../include
CFLAGS = $(INCLUDE) -DIS_64 -ieee_with_inexact -pthread -DOSF1
LDFLAGS = -shared -all -expect_unresolved "*" -taso


OBJS = testsaslbind.o testpreop.o testpostop.o testextendedop.o testentry.o testbind.o testgetip.o testdatainterop.o testdbinterop.o

all: libtest-plugin.so

libtest-plugin.so: $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $(OBJS)

.c.o:
	$(CC) $(CFLAGS) -c $<

clean:
	-rm -f $(OBJS) libtest-plugin.so

