#
# BEGIN COPYRIGHT BLOCK
# Copyright 2001 Sun Microsystems, Inc.
# Portions copyright 1999, 2001-2003 Netscape Communications Corporation.
# All rights reserved.
# END COPYRIGHT BLOCK
#
# Makefile for Directory Server plug-in
#

CC = cl
LD = link


TARGET=testplugin

OBJS=testsaslbind.obj testextendedop.obj testpreop.obj testpostop.obj testentry.obj testbind.obj testgetip.obj testdatainterop.obj testdbinterop.obj


INC = ../include
CFLAGS = /nologo -I $(INC) /c
LDFLAGS = /dll /nologo
LIBS=/DEFAULTLIB:kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib wsock32.lib ../lib/libslapd.lib ../lib/libnspr4.lib ./lib/libdb42.lib


all:						\
	init					\
	$(TARGET).dll

init:
	"c:\program files\microsoft visual studio\vc98\bin\vcvars32.bat"


$(TARGET).dll: $(OBJS)
	$(LD) $(LDFLAGS) /def:$(TARGET).def /out:$(TARGET).dll $(EXTRA_LIBS) $(LIBS) $(OBJS)
	-rm -f $(OBJS2) *~

%.obj:%.c
	$(CC) $(CFLAGS) $<

clean:
	del -f $(OBJS) $(TARGET).dll *~



