#
# BEGIN COPYRIGHT BLOCK
# Copyright (C) 2001 Sun Microsystems, Inc. Used by permission.
# Copyright (C) 2005 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK
#
# IRIX Makefile for Directory Server plug-in examples
#

CC = cc
LD = ld 

INCLUDE_FLAGS = -I../include
CFLAGS = $(INCLUDE_FLAGS) -D_SGI_MP_SOURCE -fullwarn
LDFLAGS = -32 -shared

OBJS = testsaslbind.o testextendedop.o testpreop.o testpostop.o testentry.o testbind.o testgetip.o testdatainterop.o testdbinterop.o

all: libtest-plugin.so


libtest-plugin.so: $(OBJS)
	$(LD) $(LDFLAGS) -o $@ $(OBJS)

.c.o:
	$(CC) $(CFLAGS) -c $<

clean:
	-rm -f $(OBJS) libtest-plugin.so

