#!/bin/sh  
#
# BEGIN COPYRIGHT BLOCK
# Copyright (C) 2001 Sun Microsystems, Inc. Used by permission.
# Copyright (C) 2005 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK
#
# usage unixstrip <location> 

perl="$1"

arch=`uname -s`
if [ "$arch" = "HP-UX" ]; then
    SHLIB_PATH="$4"
	export SHLIB_PATH
else
    LD_LIBRARY_PATH="$4"
	export LD_LIBRARY_PATH
fi

if [ $# > 2 ]; then
exec "$perl" unixstrip.pl "$2" "$3"
else
exec "$perl" unixstrip.pl "$2"
fi

#for StripFile in `find . -type f  -print `
#do
#	strip $StripFile
#done
