#!/bin/sh
#
# BEGIN COPYRIGHT BLOCK
# This Program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 2 of the License.
# 
# This Program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along with
# this Program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA.
# 
# In addition, as a special exception, Red Hat, Inc. gives You the additional
# right to link the code of this Program with code not covered under the GNU
# General Public License ("Non-GPL Code") and to distribute linked combinations
# including the two, subject to the limitations in this paragraph. Non-GPL Code
# permitted under this exception must only link to the code of this Program
# through those well defined interfaces identified in the file named EXCEPTION
# found in the source code files (the "Approved Interfaces"). The files of
# Non-GPL Code may instantiate templates or use macros or inline functions from
# the Approved Interfaces without causing the resulting work to be covered by
# the GNU General Public License. Only Red Hat, Inc. may make changes or
# additions to the list of Approved Interfaces. You must obey the GNU General
# Public License in all respects for all of the Program code and other code used
# in conjunction with the Program except the Non-GPL Code covered by this
# exception. If you modify this file, you may extend this exception to your
# version of the file, but you are not obligated to do so. If you do not wish to
# do so, delete this exception statement from your version. 
# 
# 
# Copyright (C) 2001 Sun Microsystems, Inc. Used by permission.
# Copyright (C) 2005 Red Hat, Inc.
# All rights reserved.
# END COPYRIGHT BLOCK
#

# determine server root directory from $0; this script is being run
# from server root/bin/slapd/admin/bin

sroot=`echo $0 | sed 's#/bin/slapd/admin/bin/.*##g'`

# check if Solaris 9+ specific un-installation
for arg in $* ; do
        if [ "$arg" = "-S" ]; then
                iDSISolaris=1
        fi
done

if [ "$iDSISolaris" = "1" ]; then
        vardir=`echo $sroot | sed 's#/usr/iplanet/#/var/#'`
        etcdir=`echo $sroot | sed 's#/usr/#/etc/#'`
fi

# search for all slapd-* directories

cd $sroot || {
	echo "Could not change dir to server root directory $sroot"
	exit 1
}

NETSITE_ROOT=$sroot
REQUEST_METHOD=GET
export NETSITE_ROOT REQUEST_METHOD
# for each server instance
for dir in slapd-* ; do
	QUERY_STRING="InstanceName=$dir"
	SERVER_NAMES=$dir
	export QUERY_STRING SERVER_NAMES
	# try to remove the nice way . . .
	cd bin/slapd/admin/bin
	status=0
	./ds_remove $* > /dev/null 2>&1 || status=$?
	cd $sroot
	# wait for that to finish
	sleep 2
	if [ $status -ne 0 -o -d $dir ]; then
		# something went wrong; kill with extreme prejudice . . .
		# Solaris 9+ specific un-installation
        if [ -f $dir/logs/pid ]; then
			pid=`cat $dir/logs/pid`
			# kill the server
			kill -9 $pid > /dev/null 2>&1
			# wait for it to stop
			sleep 2
		fi
		# remove the instance directory
		rm -rf $dir
	fi
	# Solaris 9+ specific un-installation
        if [ "$iDSISolaris" = "1" ]; then
                rm -rf $etcdir/$dir
                rm -rf $vardir/$dir
        fi

done

# remove some other stuff which is dynamically created
if [ "$iDSISolaris" = "" ]; then
	rm -rf bin/slapd
fi

exit 0
