.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DB2BAK.PL 8 "Mar 5, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME 
db2bak.pl - Directory Server perl script for creating a backup
.SH SYNOPSIS
db2bak.pl [-Z serverID] [-D rootdn] { -w password | -w - | -j filename }  [-t dbtype] [-a backupdir] [-P protocol] [-v] [-h]
.SH DESCRIPTION
Creates a backup of the Directory Server database.  The 
Directory Server must be started prior to running this script.
.SH OPTIONS
A summary of options is included below:
.TP
.B \fB\-Z\fR \fIServer Identifier\fR
The server ID of the Directory Server instance.  If there is only 
one instance on the system, this option can be skipped.
.TP
.B \fB\-D\fR \fIRoot DN\fR
The Directory Manager DN, or root DN.  If not specified, the script will 
search the server instance configuration for the value.
.TP
.B \fB\-w\fR \fIpassword\fR
The rootdn password.
.TP
.B \fB\-w -\fR 
.br
Prompt for the rootdn password.
.TP
.B \fB\-j\fR \fIpassword filename\fR
The name of the file that contains the root DN password.
.TP
.B \fB\-t\fR \fIdatabase type\fR
The backend database type (default: ldbm database).
.TP
.B \fB\-a\fR \fIbackupdir\fR
The directory where the backup should be stored.
.TP
.B \fB\-P\fR \fIProtocol\fR
The connection protocol to connect to the Directory Server.  Protocols are STARTTLS, LDAPS, LDAPI, and LDAP.
If this option is skipped, the most secure protocol that is available is used.  For LDAPI, AUTOBIND is also
available for the root user.
.TP
.B \fB\-v\fR 
.br
Display verbose ouput
.TP
.B \fB\-h\fR 
.br
Display usage
.SH EXAMPLE
.TP
db2bak.pl -Z instance1 -D 'cn=directory manager' -w password -a /LDAP/backups/20130305 -P LDAPI

Note: LDAPI must be enabled to use this protocol.  If LDAPI is not available it will default to next strongest/available protocol automatically.
.SH DIAGNOSTICS
Exit status is zero if no errors occur.  Errors result in a 
non-zero exit status and a diagnostic message being written 
to standard error.
.SH AUTHOR
db2bak.pl was written by the 389 Project.
.SH "REPORTING BUGS"
Report bugs to http://bugzilla.redhat.com.
.SH COPYRIGHT
Copyright \(co 2013 Red Hat, Inc.
