.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DBMON.SH 8 "Mar 20, 2017"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME 
dbmon.sh - Directory Server script for monitoring database and entry cache usage
.SH SYNOPSIS
[INCR=num] [SERVID=server_id][BINDDN=binddn] [BINDPW=password] [DBLIST=databases] [INDEXLIST=indexes] [VERBOSE=num] dbmon.sh
.SH DESCRIPTION
dbmon.sh is a tool used to monitor database and entry cache usage. It is especially useful for database cache and entry/dn cache tuning - how much space is left, is the cache full, how much space on average do I need per entry/dn.
.SH OPTIONS
It doesn't take any command line arguments, so all options must be passed in as environment variables.

dbmon.sh will loop repeatedly showing the db information until it is killed or Ctrl-C

All arguments are optional, but you will most likely have to provide BINDPW

.TP
.B \fBINCR\fR - show results every INCR seconds - default is 1 second
.TP
.B \fBSERVID\fR - Name of the server instance
.TP
.B \fBBINDDN\fR - DN to use to bind - must have permission to read everything under cn=config - default is cn=Directory Manager
.TP
.B \fBBINDPW\fR - password for BINDDN - default is secret
.TP
.B \fBDBLIST\fR - a list of databases you want to check - default is "all"; for more than one, delimit with spaces e.g. DBLIST="one two three"
.TP
.B \fBINDEXLIST\fR - a list of indexes to show for each named database - default is none; specify "all" for all indexes, or named e.g. INDEXLIST="id2entry entryrdn"
.TP
.B \fBVERBOSE\fR - output level - 0 == suitable for parsing by a script - 1 == has column headings - 2 == provides detailed descriptions of the data - default is 0

.SH EXAMPLE
INCR=1 SERVID=slapd-localhost BINDDN="cn=directory manager" BINDPW="secret" VERBOSE=2 dbmon.sh

.SH AUTHOR
dbmon.sh was written by the 389 Project.
.SH "REPORTING BUGS"
Report bugs to https://github.com/389ds/389-ds-base/issues/new
.SH COPYRIGHT
Copyright \(co 2017 Red Hat, Inc.
