.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH UPGRADEDB 8 "Mar 5, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME 
upgradedb - Directory Server script for upgrading the database
.SH SYNOPSIS
upgradedb [-a archivedir] [-Z serverID] [-f] [-v] [-d debuglevel] [-h]
.SH DESCRIPTION
Checks the DB version and if it has the old index formatting then it will rebuild the indexes.  This is usually needed after migrating from older versions of Directory Server.  This script must be run while the server is stopped.
.SH OPTIONS
A summary of options is included below:
.TP
.B \fB\-n\fR \fIBackend Name\fR
The name of the LDBM database to reindex.  Example: userRoot
.TP
.B \fB\-a\fR \fIDatabase directory\fR
The full path to the database directory.
.TP
.B \fB\-Z\fR \fIServer Identifier\fR
The server ID of the Directory Server instance.  If there is only 
one instance on the system, this option can be skipped.
.TP
.B \fB\-N\fR
Only checks whether any DNs in the database need to be updated. 
.TP
.B \fB\-h\fR
.br
Display the usage.
.SH EXAMPLE
.TP
upgradedb -Z instance2
.SH DIAGNOSTICS
Exit status is zero if no errors occur.  Errors result in a 
non-zero exit status and a diagnostic message being written 
to standard error.
.SH AUTHOR
upgradedb was written by the 389 Project.
.SH "REPORTING BUGS"
Report bugs to http://bugzilla.redhat.com.
.SH COPYRIGHT
Copyright \(co 2013 Red Hat, Inc.

