#!/bin/sh

PATH=$prefix/usr/lib/mozldap6:/usr/lib/mozldap6
LD_LIBRARY_PATH=$prefix/usr/lib/dirsec:/usr/lib/dirsec:$prefix/usr/lib/dirsec:$prefix/usr/lib:/usr/lib/dirsec
export LD_LIBRARY_PATH
SHLIB_PATH=$prefix/usr/lib/dirsec:/usr/lib/dirsec:$prefix/usr/lib/dirsec:$prefix/usr/lib:/usr/lib/dirsec
export SHLIB_PATH

if [ "x$1" != "x" ];
then MDN="$1";
else MDN="cn=monitor";
 fi
ldapsearch -p {{SERVER-PORT}} -b "$MDN" -s base "objectClass=*"
