#!/bin/sh

prefix="{{DS-ROOT}}"
PATH=$prefix/usr/lib/mozldap6:/usr/lib/mozldap6
LD_LIBRARY_PATH=$prefix/usr/lib/dirsec:/usr/lib/dirsec:$prefix/usr/lib/dirsec:$prefix/usr/lib:/usr/lib/dirsec
export LD_LIBRARY_PATH
SHLIB_PATH=$prefix/usr/lib/dirsec:/usr/lib/dirsec:$prefix/usr/lib/dirsec:$prefix/usr/lib:/usr/lib/dirsec
export SHLIB_PATH

ldapmodify -a -p {{SERVER-PORT}} -D "$1" -w "$2" -f $3
