#!/bin/sh

prefix="{{DS-ROOT}}"
LD_LIBRARY_PATH=$prefix/{{SERVER-DIR}}:$prefix/usr/lib/dirsec:$prefix/usr/lib:/usr/lib/dirsec
export LD_LIBRARY_PATH
SHLIB_PATH=$prefix/{{SERVER-DIR}}:$prefix/usr/lib/dirsec:$prefix/usr/lib:/usr/lib/dirsec
export SHLIB_PATH

cd {{SERVERBIN-DIR}}
if [ "$#" -eq 1 ]
then
	bak_dir=$1
else
	bak_dir={{BAK-DIR}}/`date +%Y_%m_%d_%H_%M_%S`
fi

./ns-slapd db2archive -D {{CONFIG-DIR}} -a $bak_dir
