//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dsinst.rc
//
#define ERR_NO_WINSOCK                  1
#define ERR_NO_WINSOCK_VER              2
#define ERR_NO_HOST                     3
#define ERR_NO_PORT                     4
#define ERR_NO_SUFFIX                   5
#define ERR_NO_BIND_DN                  6
#define ERR_NO_PW                       7
#define ERR_INIT_DIALOG                 8
#define ERR_NO_SERVER_ID                9
#define ERR_SERVER_ID_EXISTS            10
#define ERR_INVALID_PORT                11
#define ERR_PW_TOO_SHORT                12
#define ERR_NO_PW_AGAIN                 13
#define ERR_PW_DIFFER                   14
#define ERR_NO_ROOT_DN                  15
#define ERR_NO_SS_ADMIN                 16
#define ERR_NO_SUPPLIER_DN              17
#define ERR_NO_CHANGELOG_DB             18
#define ERR_NO_CHANGELOG_SUFFIX         19
#define ERR_NO_CONSUMER_DN              20
#define ERR_READ_GLOBAL_CACHE           21
#define ERR_READ_LOCAL_CACHE            22
#define ERR_NO_FIND_INST_PROG           23
#define ERR_EXEC_INST_PROG              24
#define ERR_NO_STAT_TMP_FILE            25
#define ERR_NO_CREATE_FILE              26
#define ERR_CREATE_MCC_BAT              27
#define ERR_CREATE_DS_INSTANCE          28
#define ERR_REMOVE_EVLOG_KEY            29
#define ERR_REMOVE_INSTANCE             30
#define ERR_REM_INST_REG_KEYS           31
#define ERR_SERV_RUN_ON_PORT            32
#define ERR_INVALID_HOST                33
#define ERR_CANT_FIND_DS                34
#define ERR_SNMP_IS_RUNNING             35
#define ERR_SNMP_BAD_SHUTDOWN           36
#define ERR_SNMP_BAD_STARTUP            37
#define ERR_SLAPD_SHUTDOWN              38
#define ERR_UNK_INST_CREATE             39
#define IDS_UG_DESC                     40
#define IDS_UG_GB_DESC                  41
#define IDS_UG_RADIO_EXIST              42
#define IDS_UG_RADIO_CREATE             43
#define IDS_UG_DLG_CAPTION              44
#define ERR_NO_ADMIN_DOMAIN             45
#define ERR_8BIT_PW                     46
#define ERR_8BIT_SERVID                 47
#define ERR_8BIT_PATH                   48
#define SUM_DS_SET_TITLE                49
#define SUM_SERVER_IDENTIFIER           50
#define SUM_SUFFIX                      51
#define SUM_PORT                        52
#define SUM_CONFIG_DS_TITLE             53
#define SUM_HOST                        54
#define SUM_BIND_AS                     55
#define SUM_DATA_DS_TITLE               56
#define SUM_CFG_ADM_ID                  57
#define SUM_ADMIN_DOMAIN                58
#define SUM_DIRECTORY_MANAGER           59
#define SUM_SUPPLIER_REPL_TITLE         60
#define SUM_CHANGELOG_DB_DIR            61
#define SUM_CHANGELOG_SUFFIX            62
#define SUM_REPL_AGR_TITLE              63
#define SUM_REPL_ROOT                   64
#define SUM_REPL_DAYS                   65
#define SUM_REPL_TIMES                  66
#define SUM_CONSUMER_BIND_DN            67
#define SUM_CONSUMER_REPL_TITLE         68
#define SUM_SUPPLIER_DN                 69
#define SUM_REPL_SYNC_INTERVAL          70
#define SUM_POP_ORG_STRUCT              71
#define SUM_POP_DB_FILE                 72
#define SUM_DISABLE_SCHEMA_CHECKING     73
#define ERR_INVALID_DN                  74
#define SUM_REINSTALL                   75
#define ERR_CANT_FIND_DS_REPL           76
#define IDS_STARTING_SERVICE            77
#define IDS_STOPPING_SERVICE            78
#define IDS_WAIT_SERVICE_START          79
#define IDS_WAIT_SERVICE_STOP           80
#define ERR_ADMIN_DOMAIN_DN             81
#define ERR_CANT_FIND_ADMIN_DOMAIN      82
#define WARN_USING_LDAPV2_QUOTES        83
#define ERR_8BIT_UID                    84
#define ERR_SERVER_ID_EXISTS_TITLE      85
#define ERR_NO_CONFIG_URL               86
#define WARN_USING_LDAPV2_QUOTES_TITLE  87
#define ERR_INVALID_DN_TITLE            88
#define ERR_NO_WINSOCK_TITLE            89
#define ERR_NO_WINSOCK_VER_TITLE        90
#define ERR_8BIT_SERVID_TITLE           91
#define ERR_SERV_RUN_ON_PORT_TITLE      92
#define ERR_INIT_DIALOG_TITLE           93
#define ERR_NO_HOST_TITLE               94
#define ERR_NO_PORT_TITLE               95
#define ERR_NO_SUFFIX_TITLE             96
#define ERR_NO_BIND_DN_TITLE            97
#define ERR_NO_PW_TITLE                 98
#define ERR_NO_SERVER_ID_TITLE          99
#define ERR_INVALID_PORT_TITLE          100
#define ERR_PW_TOO_SHORT_TITLE          101
#define IDB_WIZARD                      102
#define ERR_NO_PW_AGAIN_TITLE           102
#define ERR_PW_DIFFER_TITLE             103
#define ERR_NO_ROOT_DN_TITLE            104
#define IDD_SERVER_SETTINGS             105
#define ERR_NO_SS_ADMIN_TITLE           105
#define IDD_SUITESPOTID                 106
#define ERR_NO_SUPPLIER_DN_TITLE        106
#define IDD_CONSUMER_REPLICATION_SETTINGS 107
#define ERR_NO_CHANGELOG_DB_TITLE       107
#define IDD_SUPPLIER_REPLICATION_SETTINGS 108
#define ERR_NO_CHANGELOG_SUFFIX_TITLE   108
#define IDD_ROOTDN                      109
#define ERR_NO_CONSUMER_DN_TITLE        109
#define ERR_NO_FIND_INST_PROG_TITLE     110
#define ERR_EXEC_INST_PROG_TITLE        111
#define IDD_CHOOSE_REPLICATION_SETUP    112
#define ERR_NO_STAT_TMP_FILE_TITLE      112
#define IDD_REPLICATION_AGREEMENT       113
#define ERR_NO_CREATE_FILE_TITLE        113
#define ERR_CREATE_MCC_BAT_TITLE        114
#define IDD_SAMPLE_ENTRIES_ORG          115
#define ERR_CREATE_DS_INSTANCE_TITLE    115
#define IDD_CONSUMER_DN                 116
#define ERR_REMOVE_EVLOG_KEY_TITLE      116
#define IDD_MCC_SETTINGS                117
#define ERR_REMOVE_INSTANCE_TITLE       117
#define ERR_REM_INST_REG_KEYS_TITLE     118
#define IDD_DISABLE_SCHEMA_CHECKING     119
#define ERR_INVALID_HOST_TITLE          119
#define IDD_ADMIN_DOMAIN                120
#define ERR_CANT_FIND_DS_TITLE          120
#define IDD_REINSTALL_CONFIG            121
#define ERR_SNMP_IS_RUNNING_TITLE       121
#define IDD_UNINSTALL_STATUS            122
#define ERR_SNMP_BAD_SHUTDOWN_TITLE     122
#define ERR_SNMP_BAD_STARTUP_TITLE      123
#define IDD_ADMIN_ID_ONLY               123
#define ERR_SLAPD_SHUTDOWN_TITLE        124
#define ERR_NO_ADMIN_DOMAIN_TITLE       125
#define ERR_8BIT_PW_TITLE               126
#define ERR_8BIT_PATH_TITLE             127
#define ERR_CANT_FIND_DS_REPL_TITLE     128
#define ERR_ADMIN_DOMAIN_DN_TITLE       129
#define ERR_CANT_FIND_ADMIN_DOMAIN_TITLE 130
#define ERR_8BIT_UID_TITLE              131
#define ERR_NO_CONFIG_URL_TITLE         132
#define ERR_NO_USER_URL                 133
#define ERR_NO_USER_URL_TITLE           134
#define ERR_UNINSTALL_DS                135
#define ERR_UNINSTALL_DS_TITLE          136
#define ERR_REG_DEL_KEY_TITLE           137
#define ERR_REG_DEL_KEY                 138
#define ERR_REG_CREATE_KEY_TITLE        139
#define ERR_REG_CREATE_KEY              140
#define IDC_EDIT_UNRESTRICTED_USER      1000
#define IDC_EDIT_PASSWORD               1001
#define IDC_EDIT_PASSWORD_AGAIN         1002
#define IDC_STATIC_UNRESTRICTED_USER    1003
#define IDC_STATIC_PASSWORD             1004
#define IDC_STATIC_PASSWORD_AGAIN       1005
#define IDC_STATIC_PASSWORD_AGAIN2      1006
#define IDC_STATIC_SERVER_PORT          1012
#define IDC_STATIC_SECURITY_ENABLED     1013
#define IDC_STATIC_SERVER_IDENTIFIER    1014
#define IDC_STATIC_SUFFIX               1015
#define IDC_STATIC_SECURE_SERVER_PORT   1016
#define IDC_EDIT_SERVER_IDENTIFIER      1017
#define IDC_EDIT_SUFFIX                 1018
#define IDC_EDIT_SERVER_PORT            1019
#define IDC_STATIC_GENERAL_SETTINGS     1020
#define IDC_EDIT_SECURE_SERVER_PORT     1021
#define IDC_STATIC_SECURITY_SETTINGS    1022
#define IDC_RADIO_SEC_YES               1023
#define IDC_RADIO_SEC_NO                1024
#define IDC_SPIN_SERVER_PORT            1025
#define IDC_SPIN_SECURE_SERVER_PORT     1026
#define IDC_STATIC_CIR_DESCRIPTION      1027
#define IDC_EDIT_SUITESPOT_USER         1028
#define IDC_STATIC_CIR_DESCRIPTION2     1028
#define IDC_STATIC_SUPPLIER_DN          1029
#define IDC_STATIC_SUITESPOT_USER       1030
#define IDC_STATIC_SUPPLIER_PW          1031
#define IDC_STATIC_SUPPLIER_PW2         1032
#define IDC_EDIT_SUPPLIER_DN            1033
#define IDC_EDIT_SUPPLIER_PW            1034
#define IDC_SUPPLIER_PW_AGAIN           1035
#define IDC_CONSUMER                    1036
#define IDC_STATIC_SUPPLIER_SSL         1037
#define IDC_EDIT_SUPPLIER_SSL_CLIENTS   1038
#define IDC_STATIC_SIR_DESCRIPTION      1039
#define IDC_STATIC_CHANGELOG_DB_DIR     1040
#define IDC_STATIC_CHANGELOG_SUFFIX     1041
#define IDC_STATIC_MAX_CHANGELOG_RECORDS 1042
#define IDC_STATIC_MAX_CHANGELOG_RECORDS2 1043
#define IDC_EDIT_CHANGELOG_DB_DIR       1044
#define IDC_EDIT_CHANGELOG_DB_SUFFIX    1045
#define IDC_EDIT_MAX_CHANGELOG_AGE      1046
#define IDC_EDIT_MAX_CHANGELOG_RECORDS  1047
#define IDC_COMBO_MAX_CHANGELOG_AGE     1049
#define IDC_SIR_DESCRIPTION             1050
#define IDC_STATIC_SIR_AGREEMENTS       1051
#define IDC_STATIC_SIR_AGREEMENTS_GROUP 1052
#define IDC_LIST_CONSUMERS              1053
#define IDC_RADIO_CONSUMER_CIR          1056
#define IDC_STATIC_SIR_AGREEMENTS2      1057
#define IDC_RADIO_CONSUMER_SIR          1057
#define IDC_STATIC_CIR_AGREEMENTS_GROUP 1058
#define IDC_RADIO_SUPPLIER_SIR          1058
#define IDC_RADIO_SUPPLIER_CIR          1059
#define IDC_STATIC_CHANGELOG_DB_DIR2    1060
#define IDC_RADIO_NO_REPLICATION        1060
#define IDC_RADIO_NO_CONSUMER_REPLICATION 1060
#define IDC_STATIC_REPLICA_CONFIG       1061
#define IDC_RADIO_NO_SUPPLIER_REPLICATION 1061
#define IDC_STATIC_REPLICATION_HOST     1062
#define IDC_STATIC_REPLICATION_PORT     1063
#define IDC_STATIC_REPLICATION_ROOT     1064
#define IDC_STATIC_REPLICATION_BIND_AS  1065
#define IDC_STATIC_REPLICATION_PW       1066
#define IDC_EDIT_REPLICATION_HOST       1067
#define IDC_EDIT_REPLICATION_ROOT       1068
#define IDC_EDIT_REPLICATION_BIND_AS    1069
#define IDC_EDIT_REPLICATION_PW         1070
#define IDC_EDIT_REPLICATION_PORT       1071
#define IDC_STATIC_REPLICATION_AGREEMENT 1072
#define IDC_CHECK_REPLICATION_SSL       1073
#define IDC_STATIC_SAMPLE_ENTRIES_DESCRIPTION 1074
#define IDC_CHECK_SAMPLE_ENTRIES        1075
#define IDC_CHECK_POPULATE_SAMPLE_ENTRIES 1075
#define IDC_STATIC_ORG_ENTRIES          1076
#define IDC_CHECK_POPULATE_ORG_ENTRIES  1077
#define IDC_STATIC_SAMPLE_GROUP         1078
#define IDC_STATIC_DEFAULT_ORG_GROUP    1079
#define IDC_EDIT_CONSUMER_DN            1080
#define IDC_STATIC_CONSUMER_DN          1081
#define IDC_STATIC_CONSUMER_PW          1082
#define IDC_STATIC_SUPPLIER_CIR         1083
#define IDC_STATIC_UNRESTRICTED_USER_GROUPBOX 1084
#define IDC_STATIC_SUITESPOT_ADMIN_GROUPBOX 1085
#define IDC_STATIC_CONSUMER_CIR_EXTRA   1086
#define IDC_STATIC_CONSUMER_SIR_EXTRA   1087
#define IDC_STATIC_SUPPLIER_CIR_EXTRA   1088
#define IDC_STATIC_SUPPLIER_SIR_EXTRA   1089
#define IDC_STATIC_CONSUMER_REPL        1090
#define IDC_STATIC_SUPPLIER_REPLICATION 1091
#define IDC_BUTTON_CHOOSE_LDIF_FILE     1093
#define IDC_RADIO_DONT_POPULATE         1097
#define IDC_RADIO_POPULATE_SAMPLE       1098
#define IDC_RADIO_POPULATE_CUSTOM       1099
#define IDC_STATIC_MUST_HAVE_BASE       1100
#define IDC_STATIC_FILE_NAME_COLON      1101
#define IDC_STATIC_LDIF_FILE_NAME       1102
#define IDC_STATIC_REPL_DAYS            1103
#define IDC_CHECK_SUN                   1104
#define IDC_CHECK_MON                   1105
#define IDC_CHECK_TUE                   1106
#define IDC_CHECK_WED                   1107
#define IDC_CHECK_THUR                  1108
#define IDC_CHECK_FRI                   1109
#define IDC_CHECK_SAT                   1110
#define IDC_STATIC_REPL_START_TIME      1111
#define IDC_EDIT_REPL_START_TIME_HH     1112
#define IDC_STATIC_REPL_END_TIME        1113
#define IDC_EDIT_REPL_END_TIME_HH       1114
#define IDC_SPIN_REPL_START_TIME_MM     1115
#define IDC_SPIN_REPL_SYNC_INTERVAL     1117
#define IDC_EDIT_REPL_SYNC_INTERVAL     1118
#define IDC_EDIT_REPL_START_TIME_MM     1119
#define IDC_STATIC_REPL_SYNC            1120
#define IDC_SPIN_REPL_START_TIME_HH     1121
#define IDC_SPIN_REPL_END_TIME_HH       1122
#define IDC_EDIT_REPL_END_TIME_MM       1123
#define IDC_SPIN_REPL_END_TIME_MM       1124
#define IDC_EDIT_MCC_HOST               1125
#define IDC_EDIT_HOST                   1125
#define IDC_EDIT_MCC_PORT               1126
#define IDC_EDIT_PORT                   1126
#define IDC_EDIT_MCC_SUFFIX             1127
#define IDC_EDIT_MCC_BIND_AS            1128
#define IDC_EDIT_BIND_AS                1128
#define IDC_EDIT_MCC_PW                 1129
#define IDC_EDIT_PW                     1129
#define IDC_STATIC_MCC_HOST             1130
#define IDC_STATIC_MCC_PORT             1131
#define IDC_STATIC_MCC_SUFFIX           1132
#define IDC_STATIC_MCC_BIND_AS          1133
#define IDC_STATIC_MCC_PW               1134
#define IDC_STATIC_MCC_SETTINGS         1135
#define IDC_STATIC_SETTINGS             1135
#define IDC_RADIO_MCC_USE_THIS_SERVER   1136
#define IDC_RADIO_USE_THIS_SERVER       1136
#define IDC_RADIO_MCC_USE_EXISTING_SERVER 1137
#define IDC_RADIO_USE_EXISTING_SERVER   1137
#define IDC_STATIC_MCC_DESC             1138
#define IDC_STATIC_DESC                 1138
#define IDC_STATIC_MCA_DESC             1139
#define IDC_STATIC_DM_DESC              1140
#define IDC_RADIO_CONFIG_CONSUMER_DN_YES 1142
#define IDC_RADIO3                      1143
#define IDC_RADIO_CONFIG_CONSUMER_DN_NO 1143
#define IDC_STATIC_DISABLE_SCHEMA_TXT   1144
#define IDC_STATIC_DISABLE_SCHEMA_CHECKING_GROUP 1145
#define IDC_CHECK_DISABLE_SCHEMA_CHECKING 1146
#define IDC_STATIC_DISABLE_SCHEMA_TEXT_CONT 1147
#define IDC_STATIC_SERV_SETTINGS_DESC   1148
#define IDC_EDIT_ADMIN_DOMAIN           1149
#define IDC_STATIC_ADMIN_DOMAIN_DESC    1150
#define IDC_STATIC_ADMIN_DOMAIN         1151
#define IDC_STATIC_ADMIN_DOMAIN_GB      1152
#define IDC_STATIC_ADMIN_DOMAIN_DESC2   1153
#define IDC_STATIC_ADMIN_REINSTALL_DESC 1154
#define IDC_STATIC_ADMIN_DOMAIN_DESC3   1155
#define IDC_CONFIG_URL_VAL              1156
#define IDC_STATIC_BIND_AS              1157
#define IDC_STATIC_PW                   1158
#define IDC_STATIC_CONFIG_DIR_SETTING   1161
#define IDC_STOPPING_SERVER_MESSAGE     1163

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1166
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
