[package]
name = "rsds"
version = "0.1.0"
authors = ["William Brown <william@blackhats.net.au>"]
edition = "2018"

[dependencies]

[lib]
path = "sds/lib.rs"
name = "rsds"
crate-type = ["staticlib", "lib"]

[profile.release]
panic = "abort"
lto = true


