.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH DS-REPLCHECK 1 "May 2, 2017"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME 
ds-cockpit-setup - Install the 389 Directory Server Cockpit UI plugin

.SH SYNOPSIS
ds-cockpit-setup [-h, --help] [-v, --verbose] [-i, --install] [-t, --testing] [-u, --update]

.SH DESCRIPTION
ds-cockpit-setup installs the Directory Server management Cockpit UI Plugin 
into either the default Cockpit plugin location, or the user's home directory 
Cockpit location (typically this is used for testing).

For more information on Cockpit please see:

    http://cockpit-project.org

    https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html-single/getting_started_with_cockpit/


.SH OPTIONS

A summary of options is included below:

.TP
.B \fB\-h, \-\-help\fR
.br
Display usage
.TP
.B \fB\-i, \-\-install\fR
Install the Cockpit plugin into the default location
.TP
.B \fB\-t, \-\-testing\fR
Install the Cockpit plugin into the user's default location (~/.local/share/cockpit)
.TP
.B \fB\-u, \-\-update\fR
Update an existing Cockpit plugin installation
.TP
.B \fB\-v, \-\-verbose\fR
Write verbose output to STDOUT

.SH EXAMPLE
ds-cockpit-setup --testing --verbose

ds-cockpit-setup -i -u

.SH AUTHOR
ds-cockpit-setup was written by the 389 Project.
.SH "REPORTING BUGS"
Report bugs to https://pagure.io/389-ds-base/new_issue
.SH COPYRIGHT
Copyright \(co 2018 Red Hat, Inc.
