.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH PWDHASH 1 "May 18, 2008"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
pwdhash \- Generator of password hashes
.SH SYNOPSIS
.B pwdhash
[\fI-D config-dir\fR] [\fI-H\fR] [\fI-s scheme | -c comparepwd\fR] password
.PP
.SH DESCRIPTION
Generates password hashes which can also be used in LDIF password fields.
This uses the Directory Server password generator.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.SH OPTIONS
A summary of options is included below:
.TP
.B \-H
Show summary of options.
.TP
.B \-s scheme
Password scheme to be used (e.g. MD5, SHA1, SHA256, SHA512, 
SSHA, SSHA256, SSHA512)
.TP
.B \-c comparepassword
Password to be compared against
.TP
.B \-D configdir
Takes the password schema directly from the ns-slapd configuration
.br
.SH AUTHOR
dbscan was written by the 389 Project.
.SH "REPORTING BUGS"
Report bugs to http://bugzilla.redhat.com.
.SH COPYRIGHT
Copyright \(co 2001 Sun Microsystems, Inc. Used by permission.
.br
Copyright \(co 2008 Red Hat, Inc.
.br
This manual page was written by Michele Baldessari <michele@pupazzo.org>,
for the Debian project (but may be used by others).
.br
This is free software.  You may redistribute copies of it under the terms of
the Directory Server license found in the LICENSE file of this
software distribution.  This license is essentially the GNU General Public
License version 2 with an exception for plug-in distribution.
