
[workspace]
members = [
    "librslapd",
    "librnsslapd",
    "libsds",
    "slapd",
    "slapi_r_plugin",
    "plugins/entryuuid",
    "plugins/entryuuid_syntax",
]

[profile.release]
panic = "abort"
lto = true


