name: Coverity Scan

on:
  schedule:
    - cron:  '30 9 * * 1'

jobs:
  coverity:
    runs-on: ubuntu-24.04

    container:
      image: quay.io/389ds/ci-images:fedora

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Checkout and configure
        run: autoreconf -fvi && ./configure

      - uses: vapier/coverity-scan-action@2068473c7bdf8c2fb984a6a40ae76ee7facd7a85 # v1
        with:
          project: '389ds/389-ds-base'
          command: make
          email: ${{ secrets.COVERITY_SCAN_EMAIL }}
          token: ${{ secrets.COVERITY_SCAN_TOKEN }}
