name: cppcheck
on:
  - pull_request
  - push

jobs:
  cppcheck:
    runs-on: ubuntu-20.04
    container:
      image: quay.io/389ds/ci-images:scan

    steps:
      - uses: actions/checkout@v2
      - name: Checkout and configure
        run: bash -c "(cppcheck . 2> >(tee /dev/stderr)) > log.txt"

      - uses: actions/upload-artifact@v2
        with:
          name: cppcheck
          path: log.txt
