name: Release

on:
  push:
    tags:
      - "389-ds-base-*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/389ds/ci-images:test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ steps.get_version.outputs.version }}

      - name: Check if the tagged commit belongs to a valid branch
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          COMMIT=$(git rev-parse HEAD)
          BRANCHES=$(git branch -a --contains $COMMIT | grep -v 'HEAD detached at')
          if [ -n "$BRANCHES" ]; then
              echo "Tagged commit $COMMIT belongs to the following branch(es):"
              echo "$BRANCHES"
          else
              echo "Tagged commit $COMMIT does not belong to any branch."
              exit 1
          fi

      - name: Create tarball
        run: TAG=${{ github.ref_name}} make -f rpm.mk dist-bz2

      - name: Upload tarball
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name}}.tar.bz2
          path: ${{ github.ref_name}}.tar.bz2

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ github.ref_name}}.tar.bz2
